-- 1. Crear la tabla de Productos
CREATE TABLE PRODUCTO (
    ID_PRODUCTO INT PRIMARY KEY IDENTITY(1,1),
    DESCRIPCION VARCHAR(100),
    PRECIO DECIMAL(18,2)
);

-- 2. Crear la tabla de Envíos
CREATE TABLE ENVIO (
    ID_ENVIO INT PRIMARY KEY IDENTITY(1,1),
    ZONA VARCHAR(50),
    PRECIO DECIMAL(18,2)
);

-- 3. Crear la tabla de Pedidos (con las llaves foráneas)
CREATE TABLE PEDIDO (
    ID_PEDIDO INT PRIMARY KEY IDENTITY(1,1),
    ID_PRODUCTO INT FOREIGN KEY REFERENCES PRODUCTO(ID_PRODUCTO),
    ID_ENVIO INT FOREIGN KEY REFERENCES ENVIO(ID_ENVIO),
    CANTIDAD INT,
    MONTO_TOTAL DECIMAL(18,2),
    PRIORIDAD VARCHAR(50),
    FECHA_REGISTRO DATETIME
);